function tbl = importDataTwoColumn(strPath, strWorksheet, strRange)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    strPath: "E:\Programação\USP\relatorios\fisc_rel_2\rel_3\rel3.xlsx"
%    strWorksheet: "inclined_plane"
%    strRange: "A2:B48"
%
% Auto-generated by MATLAB on 06-Jun-2021 13:00:31

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = strWorksheet;
opts.DataRange = strRange;

% Specify column names and types
opts.VariableNames = ["x", "y"];
opts.VariableTypes = ["double", "double"];
% Import the data
tbl = readtable(strPath, opts, "UseExcel", false)

