%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Programação\USP\relatorios\fisc_rel_2\rel_3\rel3.xlsx
%    Worksheet: inclined_plane
%
% Auto-generated by MATLAB on 06-Jun-2021 13:00:31

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "inclined_plane";
opts.DataRange = "A2:B48";

% Specify column names and types
opts.VariableNames = ["time", "position"];
opts.VariableTypes = ["double", "double"];
% Import the data
tbl = readtable("E:\Programação\USP\relatorios\fisc_rel_2\rel_3\rel3.xlsx", opts, "UseExcel", false);

%% Convert to output type
time = tbl.time;
position = tbl.position;


%% Clear temporary variables
clear opts tbl

%% Variables for Exp2

positionCm = 100*position; %% For a better visualization in graph for the exp2 will be ploted in (cm/s)x(s)
 
velocity = positionCm./time;

lengthVectors = length(time);

fig = figure();

x = time;
y = velocity;

%% Least Squares For Exp2

avgY = mean(y);
avgX = mean(x);

num = 0;
dem = 0;

for i = 1:lengthVectors
    num = num + (x(i)-avgX)*y(i);
    dem = dem + (x(i)-avgX)^2;
end

a = num / dem;
b = avgY - a*avgX;

y = a*time + b;

numDeltaY = 0;
numDeltaB = 0;
demDeltaY = lengthVectors-2;

for i = 1:lengthVectors
  numDeltaY = numDeltaY + (a*x(i)+b-y(i))^2;
  numDeltaB = numDeltaB + x(i)^2;
end

deltaY = sqrt(numDeltaY/demDeltaY);
deltaA = deltaY/sqrt(dem);
deltaB = (sqrt(numDeltaB/(lengthVectors*dem)))*deltaY;

plot(time, velocity, '.', 'MarkerSize', 15)
hold on

plot(time, y, 'r-', 'LineWidth', 1.5)

xlabel('Tempo (s)', 'FontName', 'Times', 'FontSize', 12)
ylabel('Velocidade (cm/s)', 'FontName', 'Times', 'FontSize', 12)
legend('Dados', 'Regressão Linear Mínimos Quadrados', 'Location', 'northwest')

grid on
hold off
clear x y
